### ISSUE TITLE
Webpage

### ISSUE THREAD

**Issue by nicrie** [ECMWFCode4Earth/sketchbook-earth#16]

**Comment by NikosMastrantonas** [comment]
The draft book is published at https://nikosmastrantonas.github.io/sketchbook-earth/intro.html
Once more progress is done in the remaining tutorials the book will be transferred to this repository

**Comment by NikosMastrantonas** [comment]
The first draft is on the personal repository.
Once all notebooks are done and feedback is received it will be pushed to this repo
https://nikosmastrantonas.github.io/sketchbook-earth/intro.html

**Comment by nicrie** [comment]
New working directory is now: https://github.com/ECMWFCode4Earth/sketchbook-earth

Page is published to: https://ecmwfcode4earth.github.io/sketchbook-earth/

**Comment by NikosMastrantonas** [comment]
https://ecmwfcode4earth.github.io/sketchbook-earth/intro.html
